const std = @import("std");

const ExceptionsPossible = packed struct { 
    domain: bool, 
    range: bool, 
    fault: bool, 
    invalid_value: bool, 
    failed: bool, 
    factor: bool, 
    sanity: bool, 
    no_mem: bool,
    bad_func: bool, 
    run_away: bool, 
    max_iter: bool, 
    zero_div: bool, 
    tol: bool, 
    underflow: bool, 
    overflow: bool, 
    loss: bool, 
    round: bool, 
    bad_len: bool, 
    not_square: bool, 
    singular: bool, 
    diverge: bool,
    unsup: bool, 
    unimpl: bool, 
    cache: bool, 
    table: bool, 
    no_prog: bool, 
    no_prog_j: bool,
    tol_f: bool, 
    tol_x: bool, 
    tol_g: bool, 
    eof: bool };

// Autogenerated reasonably, some stuff manually input
const FunctionConfig = struct {
    exceptions: ExceptionsPossible,
};
